### ISSUE TITLE
merge-request: No merge request message specified

### ISSUE THREAD

**Issue by raine** [seveas/git-spindle#101]
1. `$ git lab merge-request`
2. vim is opened with commit message as placeholder
3. save the file and exit
4. output says "No merge request message specified"

**Comment by seveas** [comment]
Was the commit message a single line?

**Comment by raine** [comment]
Yes.

**Comment by seveas** [comment]
Yeah, git-spindle requires you to specify a title and body for a merge request. That won't change, but the error message could be better.

**Comment by raine** [comment]
Okay, I'm used to not having to specify the body as that's how `gh` works and I do prefer that behavior.

**Comment by kflorence** [comment]
@seveas can body just default to an empty string?

**Comment by raine** [comment]
That would be great. 80% of the time I do this because there's nothing to expand upon.

```
blah blah

-

```

**Comment by seveas** [comment]
97b9483 adds the possibility to leave out a body for single-commit pull requests, if and only if that commit also only has a title.
