### ISSUE TITLE
Doesn't seem to work for GitLab with LDAP login

### ISSUE THREAD

**Issue by kflorence** [seveas/git-spindle#106]
```
kflorence:~/dev/mosaic/business (test)$ git lab whoami
GitLab password:
Traceback (most recent call last):
  File "/usr/local/bin/git-lab", line 11, in <module>
    GitLab().main()
  File "/usr/local/lib/python2.7/site-packages/gitspindle/__init__.py", line 311, in main
    self.login()
  File "/usr/local/lib/python2.7/site-packages/gitspindle/gitlab.py", line 65, in login
    self.login()
  File "/usr/local/lib/python2.7/site-packages/gitspindle/gitlab.py", line 47, in login
    self.gl.auth()
  File "/usr/local/lib/python2.7/site-packages/gitspindle/glapi.py", line 170, in auth
    self.credentials_auth()
  File "/usr/local/lib/python2.7/site-packages/gitspindle/glapi.py", line 181, in credentials_auth
    _raiseErrorFromResponse(r, GitlabAuthenticationError)
  File "/usr/local/lib/python2.7/site-packages/gitspindle/glapi.py", line 135, in _raiseErrorFromResponse
    response_body=response.content)
gitspindle.glapi.GitlabAuthenticationError: 401: 401 Unauthorized
```

Quite possible I am doing something wrong. Is there anyway I can just provide my API token to `.gitspindle` manually? I'm not sure where it gets stored.

**Comment by seveas** [comment]
That looks like the API is not enabled or something. You can try setting the token manually with:
```
git lab config token token-goes-here
```

**Comment by kflorence** [comment]
Oh wait, does this only work for gitlab.com? We are hosting our own GitLab EE here.

**Comment by seveas** [comment]
This works with EE as well, but you'll need to tell git lab where your EE instance lives
```
git lab config host gitlab.example.com
```

**Comment by kflorence** [comment]
@seveas Beautiful, that was the piece I was missing. I love what this project provides, thank you so much for it.

**Comment by kflorence** [comment]
Since I've got you here @seveas perhaps you can answer one further question. If I'm understanding the docs correctly, `git-spindle` should be recognizing the repository based on the remote url configured for it for commands executed within a repository. However, it seems to be using my username in place of the group assigned to the repository. For example:

```
kflorence:~/dev/mosaic/business (test)$ git remote -v
origin	git@gitlab.intranet.solarmosaic.com:mosaic/business.git (fetch)
origin	git@gitlab.intranet.solarmosaic.com:mosaic/business.git (push)
kflorence:~/dev/mosaic/business (test)$ git lab log
Repository kflorence/business could not be found on GitLab
```

Above you can see I'm in the `business` repository which is assigned to the `mosaic` group. Do I need to setup an account for "mosaic" for it to recognize this properly?

**Comment by kflorence** [comment]
@seveas FYI I'm referring to this section http://seveas.github.io/git-spindle/gitlab.html#using-multiple-accounts -- I'm not sure what it means by "If the account is on a Gitlab enterprise installation, you don’t need to use --account all the time. git-spindle will recognize the account from the url in your repository configuration"

**Comment by kflorence** [comment]
I've opened https://github.com/seveas/git-spindle/issues/107 since I'm not sure if what I'm trying to do is actually possible.
