### ISSUE TITLE
Configure per-project group?

### ISSUE THREAD

**Issue by kflorence** [seveas/git-spindle#107]
`git lab` commands seem to look for remote repositories under `username/repository`. This location is not always correct. In our case, all of our repositories are stored under groups, so for example if I'm in the repository "foo" which is hosted on gitlab as "company/foo" I need a way of telling `git-spindle` that it should look at `company/foo` instead of `username/foo` when running commands (such as `git lab log`). It seems that `git lab create` has a `--group=<group>` flag for similar purposes, but none of the other methods have this flag.

Ideally, this would be something we could configure per-repository that would get picked up automatically (for example, the git remote could be inspected: `git@gitlab.intranet.mycompany.com:mycompany/foo.git`).

**Comment by kflorence** [comment]
I can't figure out how to get around this, so this project is basically unusable to me until I get a fix/workaround.

**Comment by jackjackk** [comment]
Nott sure if it is the same problem, but I get a "Repository XXX could not be found on GitLab", with XXX being one of the repo listed in git lab repos and belonging to a group.

**Comment by Khelek** [comment]
@jackjackk I got the same message, and in my case it was related to reverse proxy config: https://github.com/gitlabhq/gitlabhq/issues/8290#issuecomment-88355554

**Comment by seveas** [comment]
Apologies for the very late response. I don't know why this fell under the radar :(

I don't see the behaviour you describe, maybe I fixed it in the mean time. 'git lab' looks at the repo specified by the gitlab id in the config. If no such id is there, it looks at the url of the 'origin' remote. This works exactly like you seem to want it, unless there's no gitlab id in the config and the origin remote points to your own fork.

**Comment by seveas** [comment]
Closing stale issue.
