### ISSUE TITLE
hub render deletes the file

### ISSUE THREAD

**Issue by Vampire** [seveas/git-spindle#116]
I use git-spindle with Git for Windows and Python for windows, installed through pip, called from a Cygwin shellscript at `/usr/local/bin/git-hub` that just calls `/c/Program\ Files/Python35/python 'C:\Program Files\Python35\Scripts\git-hub' "$@"`.

If I call `git hub render README.md`, it produces some file in %TEMP% and opens it in the already running Firefox, but before Firefox has a chance to render the file, it is deleted from disk again and only a blank page is displayed.

_Workaround:_ call `git hub render --save=/C/Users/bkautler/AppData/Local/Temp/README.html README.md` and open the generated file in Firefox

**Comment by seveas** [comment]
Yeah, it does a dodgy sleep(1) to give your browser a chance to open it. Does increasing this sleep time work for you?

**Comment by Vampire** [comment]
Well, I guess it would at least five the browser a chance to render it. But if you have maaany tabs open and Firefox needs to start first, it can need a quite long sleep. Why not let the file sitting there in the temporary directory? If you are concerned about filling up diskspace, you could add some logic so that if you call render the next time all generated files that are older than X are deleted. If you e. g. want to look at the generated HTML with `Ctrl+U` it is also unhandy if the file is not present anylonger.

**Comment by seveas** [comment]
If firefox needs to start, webbrowser.open() doesn't return until it has started, so the sleep(1) is sufficient there. It's only when firefox is already running, that webbrowser.open() returns before firefox even attempts to open the file.

Didn't think of the ctrl+u argument before, makes sense to keep the files around for that. I don't use windows myself, do you know if windows cleans up such temporary files at some point (for example at reboot)?

**Comment by Vampire** [comment]
Nope, except if that changed. But I never have seen this been done automatically. Unfortunately I have to use Windows at work. If your system disk runs out of space you go to Temp folder and clean it out manually or call the Windows Cleaner utility that does this and some other stuff.

**Comment by seveas** [comment]
Then I'm gonna go with the 5 seconds sleep, don't want to deal with cleaning up :) Does 5 seconds work for you?  You can change sleep(1) to sleep(5) on line 1324 of gitspindle/github.py to test.

**Comment by Vampire** [comment]
Hm, interesting. It is less a problem of timeout. FF just won't render the file from the temp directory. If I move it somewhere else it renders it, if it is in the temp folder it refuses to render anything

**Comment by Vampire** [comment]
No, it is not about the folder. If I copy the file in the same folder it is rendered fine

**Comment by Vampire** [comment]
More probably some issue with the tempfile mechanism that is used

**Comment by Vampire** [comment]
>  tempfile.NamedTemporaryFile([mode='w+b'[, bufsize=-1[, suffix=''[, prefix='tmp'[, dir=None[, delete=True]]]]]])

>    This function operates exactly as TemporaryFile() does, except that the file is guaranteed to have a visible name in the file system (on Unix, the directory entry is not unlinked). That name can be retrieved from the name attribute of the returned file-like object. **Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; _it cannot on Windows NT or later_)**. If delete is true (the default), the file is deleted as soon as it is closed.

**Comment by seveas** [comment]
Thanks for that, I completely missed or forgot that. Will rethink how this is done, ideas welcome. Ideally something that auto-cleans.

**Comment by Vampire** [comment]
This works for me:

    with tempfile.NamedTemporaryFile(suffix='.html', delete=False) as fd:
        fd.write(html.encode('utf-8'))
        fd.close()
        webbrowser.open('file://' + fd.name)
        time.sleep(1)
        os.remove(fd.name)

While of course it still does not allow viewing the source of the file, but for that you can still use --save as fallback or use Firebug to some extent.

**Comment by Vampire** [comment]
I provided my fix from the last comment as PR #143

**Comment by seveas** [comment]
Thanks! Merged the PR
