### ISSUE TITLE
hub render produces strange result

### ISSUE THREAD

**Issue by Vampire** [seveas/git-spindle#117]
I use git-spindle with Git for Windows and Python for windows, installed through pip, called from a Cygwin shellscript at `/usr/local/bin/git-hub` that just calls `/c/Program\ Files/Python35/python 'C:\Program Files\Python35\Scripts\git-hub' "$@"`.

If I call `git hub render --save=/C/Users/bkautler/AppData/Local/Temp/README.html README.md` for repository `vivin/gradle-semantic-build-versioning`, it produces a very strange result that you can look at in the attached file [README.zip](https://github.com/seveas/git-spindle/files/452035/README.zip).

If I replace the `\n`s by newline characters with `sed -i 's/\\n/\n/g' README.html` it almost looks correct, only the `b'` and `'` look strange then I think.

**Comment by seveas** [comment]
That looks like a missing decode()

**Comment by seveas** [comment]
Fixed in 0ed21fb

**Comment by Vampire** [comment]
Ah, yes, that looks much better, thanks
