### ISSUE TITLE
anchor links do not work in hub render output

### ISSUE THREAD

**Issue by Vampire** [seveas/git-spindle#118]
In the page generated by `git hub render`, anchorlinks do not work.

**Comment by seveas** [comment]
Not sure what you mean with that, got an example? And does it work on github?

**Comment by Vampire** [comment]
Same example as before. Render the `README.md` of `vivin/gradle-semantic-build-versioning` and try to click in the TOC. On GitHub it works fine, but not in the generated file of spindle.

**Comment by seveas** [comment]
Interesting, smells like github is doing something special there as the generated anchors are actually broken there as well. Maybe they're doing a javascript trick, or maybe I'm missing something. Will dig.

**Comment by Vampire** [comment]
Yes, they do. They prefix all anchors with `user-content-`, even manually inserted &lt;a/> tags are rewritten. https://assets-cdn.github.com/assets/github-bb7365e507a4c75141f5e042c5d5a4b321094bfb2e9aa23ddf004604c7109ef5.js then does the magic with an on-click listener that makes the links work. I guess the easiest would be to replace all `user-content-` prefixes in all anchor `id` and `name` attributes after the rendering to make the links work natively, besides including GitHub JavaScript.

**Comment by Vampire** [comment]
I submitted PR #142 that just removes all `user-content-`. Up to now I had no problem with this.

**Comment by seveas** [comment]
Cherry-picked the PR
