### ISSUE TITLE
git-lab merge-request should have default upstream branch be project default branch

### ISSUE THREAD

**Issue by mattiasb** [seveas/git-spindle#127]
In GitLab it's possible to set a projects so-called \* default branch*. 
I think it would make sense to make the default upstream branch for `git lab merge-request` be the default branch of that project instead of just chosing `master`.

We're using `git-flow` for most projects at work and have set those projects default branches to `develop` instead of master.

**Comment by seveas** [comment]
Hmm, that should already be doing the right thing, it's defaulting to what the api exposes as default_branch. Are you sure that that's configured properly in your repo?

**Comment by mattiasb** [comment]
I'll try to remember to check that tomorrow! You've been on a roll tonight, that's exciting! :)

**Comment by mattiasb** [comment]
Tested this now both on gitlab.com and at work. Works like a charm!
