### ISSUE TITLE
`git hub whoami` fails with `TypeError` (for GitHub Enterprise instance)

### ISSUE THREAD

**Issue by lecagot** [seveas/git-spindle#128]
### versions
- `aur/git-spindle-git 3.2-1 (0, 0.00) [installed: 3.2.r21.g9165e2e-1]`
- git version 2.10.0
- GitHub Enterprise Version 2.3.21
### problem description

After setting up my GitHub Enterprise account with `git-spindle` I get the following error message when trying to `whoami`:

``` bash
$ git hub whoami
Traceback (most recent call last):
  File "/usr/bin/git-hub", line 11, in <module>
    GitHub().main()
  File "/usr/lib/python3.5/site-packages/gitspindle/__init__.py", line 344, in main
    func(opts)
  File "/usr/lib/python3.5/site-packages/gitspindle/github.py", line 1436, in whoami
    self.whois(opts)
  File "/usr/lib/python3.5/site-packages/gitspindle/github.py", line 1450, in whois
    emails[email['email']] = email
TypeError: 'Email' object is not subscriptable
```

Here's the config file of `git-spindle`:

``` bash
$ cat ~/.gitspindle 
[github "company"]
        host = github.enterpri.se
        user = user
        token = ...
```

The account is properly setup, i.e. `git hub repos` gives the correct list of repositories.

Is there maybe some problem on how `git-spindle` tries to retrieve the user information from the profile page of the GitHub Enterprise instance?

**Comment by lecagot** [comment]
`git hub whois user` gives the same error:

```bash
$ git hub whois user
Traceback (most recent call last):
  File "/usr/bin/git-hub", line 11, in <module>
    GitHub().main()
  File "/usr/lib/python3.5/site-packages/gitspindle/__init__.py", line 344, in main
    func(opts)
  File "/usr/lib/python3.5/site-packages/gitspindle/github.py", line 1450, in whois
    emails[email['email']] = email
TypeError: 'Email' object is not subscriptable
```

But it works for other users:

```bash
$ git hub whois user2
User Two
Profile   https://github.enterpri.se/user2
Repos     0 public, 0 private
Gists     0 public, 0 private
```

It also works for users where the email address is retrievable from the profile page:

```bash
$ git hub whois user3
User Three
Profile   https://github.enterpri.se/user3
Email     user3@enterpri.se
Repos     4 public, 0 private
Gists     0 public, 0 private
RSA key   ...
```

So it seems to be only a problem with the own account.

**Comment by seveas** [comment]
That sounds like a github3.py compatibility issue. Which github3.py version do you use?

**Comment by seveas** [comment]
This was a github3.py 1.x issues
