### ISSUE TITLE
GitHub login flow seems broken

### ISSUE THREAD

**Issue by michaelballantyne** [seveas/git-spindle#129]
The initial login process for GitHub isn't working properly for me. I get a prompt like:

```
Password for 'https://michaelballantyne@api.github.com':
```

and enter my password, and always find it rejected.

I believe this happens because this line:
https://github.com/seveas/git-spindle/blob/master/lib/gitspindle/github.py#L39

checks the config for the token but really receives back the password produced here:
https://github.com/seveas/git-spindle/blame/master/lib/gitspindle/__init__.py#L140

and attempts to login using the password as a token (rather than a password) here:
https://github.com/seveas/git-spindle/blob/master/lib/gitspindle/github.py#L81

I hacked around it by removing 'token' from the tuple here:
https://github.com/seveas/git-spindle/blame/master/lib/gitspindle/__init__.py#L113

such that the login prompt in github.py was used instead. However, I'm not sure how to fix it in a way that matches the intent of storing the token in a credential helper, so I don't have a PR to offer.

**Comment by seveas** [comment]
Apologies for the tardiness in replying!

The line numbers of course no longer match reality, as things have changed in the mean time. But just to be sure, I deleted my cached token and reauthenticated just fine. If there was a bug in the authentication code, it's probably fixed now. If not, please file a new issue. I promise to respond quicker next time :)
