### ISSUE TITLE
Specifying repo should be optional in `git lab issues`

### ISSUE THREAD

**Issue by alerque** [seveas/git-spindle#133]
Running a  plain `git lab issues` command shows the issues for the current repository. This is great and as expected. Unfortunately when trying to add filter parameters suddenly the repo argument becomes mandatory: `git lab issues state=opened` does not work, `git lab issues group/repo state=opened` does.

This is not only counter intuitive and cumbersome but contrary to how the man page and documentation would imply by putting that in brackets. This command (as will as `git lab issue`) should assume the current  repository whenever not specified and figure out the difference between filter arguments and a repository name when only the former is specified.

**Comment by seveas** [comment]
This works as expected:

hurricane:/tmp/python-hpilo (master=)$ git lab issues
Issues for seveas/python-hpilo
[1] Test issue https://gitlab.com/seveas/python-hpilo/issues/1
hurricane:/tmp/python-hpilo (master=)$ git lab issues state=opened
Issues for seveas/python-hpilo
[1] Test issue https://gitlab.com/seveas/python-hpilo/issues/1
