### ISSUE TITLE
"git hub add-remote" silently does nothing

### ISSUE THREAD

**Issue by shlomif** [seveas/git-spindle#134]
Hi!

Thanks for git-spindle. It seems that "git hub add-remote" does nothing silently on my Mageia Linux x86-86 v6 system:

```
shlomif@telaviv1:~/progs/perl/cpan/io-all-pm$ git hub add-remote ingydotnet upstream
shlomif@telaviv1:~/progs/perl/cpan/io-all-pm$ git remote -v
origin  git@github.com:shlomif/io-all-pm.git (fetch)
origin  git@github.com:shlomif/io-all-pm.git (push)
shlomif@telaviv1:~/progs/perl/cpan/io-all-pm$ git push
Everything up-to-date
shlomif@telaviv1:~/progs/perl/cpan/io-all-pm$ git hub add-remote ingydotnet upstream && echo hello
hello
shlomif@telaviv1:~/progs/perl/cpan/io-all-pm$ git hub add-remote --ssh ingydotnet upstream && echo hello
hello
shlomif@telaviv1:~/progs/perl/cpan/io-all-pm$ git remote -v
origin  git@github.com:shlomif/io-all-pm.git (fetch)
origin  git@github.com:shlomif/io-all-pm.git (push)
shlomif@telaviv1:~/progs/perl/cpan/io-all-pm$
```

Please look into fixing it.

**Comment by seveas** [comment]
This is actually expected, as ingydotnet/io-all-pm is not a fork but the original. You'll want to use 'git hub set-origin' in this case, to set 'upstream' to ingy's repo.

**Comment by shlomif** [comment]
On Tue, 19 Sep 2017 13:36:51 -0700
Dennis Kaarsemaker <notifications@github.com> wrote:

> This is actually expected, as ingydotnet/io-all-pm is not a fork but the
> original. You'll want to use 'git hub set-origin' in this case, to set
> 'upstream' to ingy's repo.
> 

Thanks for the reply and the tip.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/humour/bits/facts/Emma-Watson/

One of my most productive days was throwing away 1,000 lines of code.
    — Ken Thompson (Attributed)

Please reply to list if it's a mailing list post - http://shlom.in/reply .
