### ISSUE TITLE
repository method only works if first remote is the canonical repo

### ISSUE THREAD

**Issue by martey** [seveas/git-spindle#135]
git-spindle automatically assumes that the first remote found is the repository's canonical remote. This is problematic if the origin of the repository changes, since git-spindle will run commands on the wrong repository unless the correct repository is explicitly set, or the order of the remotes is changed in the git config file.

Steps to reproduce:

1. git clone https://github.com/reinout/whelk.git && cd whelk
2. git remote rename origin reinout
3. git remote add origin https://github.com/seveas/whelk.git
4. git fetch origin && git branch -u origin/master
5. git hub browse

`https://github.com/reinout/whelk` is opened, instead of `https://github.com/seveas/whelk`.

I think git-spindle should prefer the current branch's remote or a remote called "origin" before using the first remote found.

**Comment by seveas** [comment]
Any way you DWIM will cause some people to be confused, so I guess that making this change will cause bug reports calling for it to be reverted. That said, treating 'origin' as higher priority does make sense, so fixed in 3a50ed5
