### ISSUE TITLE
git hub issues is missing documentation about filters

### ISSUE THREAD

**Issue by aspiers** [seveas/git-spindle#138]
http://seveas.github.io/git-spindle/github.html#issues-and-pull-requests says:

> git hub issues [<repo>] [--parent] [<filter>...]
> List all open issues. You can specify [filters](http://github3py.readthedocs.org/en/latest/repos.html#github3.repos.Repository.list_issues) to filter issues. When you specify --parent, list all open issues for the parent repository.

but the "filters" hyperlink doesn't provide anything useful, and in fact I can't find anything about filters anywhere in github3.py's docs.  Reading the source, I found

    @command
    def issues(self, opts):
        """[<repo>] [--parent] [<filter>...]
           List issues in a repository"""
        if not opts['<repo>'] and not self.in_repo:
            repos = list(self.gh.iter_repos(type='all'))
        else:
            repos = [self.repository(opts)]
        for repo in repos:
            if repo.fork and opts['--parent']:
                repo = repo.parent
            filters = dict([x.split('=', 1) for x in opts['<filter>']])
            try:
                issues = list(repo.iter_issues(**filters))

and `repo.iter_issues` seems to handle filters corresponding to [the parameters for `Repository.issues`](http://github3py.readthedocs.io/en/latest/repos.html#github3.repos.repo.Repository.issues).

Putting this altogether, I was able to get queries like this working:

    git hub issues crowbar/crowbar-core assignee=aspiers since=2017-01-01T00:00:00Z

but this is far from obvious.

**Comment by seveas** [comment]
Fixed in 254de71
