### ISSUE TITLE
FR: support searches across all repos

### ISSUE THREAD

**Issue by aspiers** [seveas/git-spindle#140]
github supports [searching across all repos](https://help.github.com/articles/searching-github/).  It would be great if git-spindle supported at least some of this.  After all, [the API is already available](https://developer.github.com/v3/search/).

In particular, this would be very useful for addressing the inadequacies in GitHub's own search.  For example, isaacs/github#833 could be worked around by implementing a new subcommand like

    git hub reviews --outstanding

which would use the global search API to search for `is:pr involved:USERNAME`, and then iterate over each of the resulting PRs, using [the (still experimental) Review Requests API](https://developer.github.com/v3/pulls/review_requests/#list-review-requests) to only list PRs for which reviews were requested and not yet provided.

**Comment by seveas** [comment]
Global search works, but is not the most obvious thing to find. Just run 'git hub issues' outside any repo :)

**Comment by aspiers** [comment]
@seveas Thanks a lot for the reply, and indeed `git hub issues` works fine (albeit slowly) with no parameters! But unfortunately I could not get it to work with filters.  [The documentation](http://seveas.github.io/git-spindle/github.html#issues-and-pull-requests) says:

> `git hub issues [<repo>] [--parent] [<filter>...]`
>
> List all open issues. You can specify [filters](http://github3py.readthedocs.org/en/latest/repos.html#github3.repos.Repository.list_issues) to filter issues. When you specify `--parent`, list all open issues for the parent repository.

but the filters hyperlink is broken since there is no documentation for `github3.repos.Repository.list_issues`.  The closest I could find is `github3.repos.Repository.issues` which suggests that something like `assignee:aspiers` should be a valid filter, but when I try this outside any git repo, I get:

    $ git hub issues assignee:aspiers
    Repository assignee:aspiers could not be found

so clearly the repo argument is not optional like it claims.

**Comment by seveas** [comment]
hmm, yes, I see where that goes wrong. Will fix.

**Comment by seveas** [comment]
Fixed in 254de71 with a code fix and better docs.

Your example works now when run outside a repo, if you replace : with =. And you can now query all repos even when inside a repo, using `git hub issues -- assignee=aspiers`

**Comment by aspiers** [comment]
Awesome, thanks a lot!
