### ISSUE TITLE
missing python-whelk dep

### ISSUE THREAD

**Issue by ildella** [seveas/git-spindle#141]
trying install on Ubuntu 16.10, after adding repo, update, here's the install output: 

:~$ sudo apt-get install git-spindle
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 git-spindle : Depends: python-whelk (>= 1.9) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by seveas** [comment]
whelk is in the dennis/python ppa.
