### ISSUE TITLE
Use git-credential to store sensitive information

### ISSUE THREAD

**Issue by mattiasb** [seveas/git-spindle#161]
Currently `git-spindle` stores its session token and username as plain text inside `.gitspindle`. I think it would be neat if git-spindle used the `git-credential` interface instead. That way the user can choose to store the data in plaintext by using `git-credential-store` or something more secure (there's backends for Linux-, MacOS- and Windows keyrings as well as lastpass.com for example).

An example of manually using git credential:
```shell
echo -e "protocol=https\nhost=gitlab.com\n" | git credential fill
protocol=https
host=gitlab.com
username=mattiasb
password=****************
```

`git-credential` could obviously be used both when adding an account and when reusing the token. I already had `gitlab.com` in my unlocked keyring for example so there's really no reason why I should have to type my username and password again when adding the account.

**Comment by seveas** [comment]
It's been doing this for exactly 2 years already :)
9bd94ec895c981d42eed61950a140bc3f8f257cb

**Comment by mattiasb** [comment]
OMG!
