### ISSUE TITLE
Can't add Gitlab token

### ISSUE THREAD

**Issue by Schnouki** [seveas/git-spindle#162]
Hi,

I'm using Gitlab with 2FA enabled. Because of this, I have to use a personal access token to login with git-spindle. First, would it be possible to document this somewhere? (At least a link to the "standard" [token creation page on gitlab.com](https://gitlab.com/profile/personal_access_tokens) + which scopes to enable).

Now the real issue: the token I created for git-spindle starts with a `-` (let's say it's `-myToken`). Because of this I couldn't add it with `git lab config token -myToken`: it just showed the doc.
I'm guessing that because of the starting dash, my token was interpreted as a command line flag. Could it be possible to fix this?
(I was able to add the token without the dash and then edit my git-credentials file to "fix" it, but this kind of sucks...)

Thanks a lot!

**Comment by seveas** [comment]
I'll see if we can somehow automate token createion even in the face of 2fa, it's possible for GitHub, so hopefully possible for GitLab too.

For the second one: that seems to be a limitation in docopt, not much I can do there I'm afraid :(

**Comment by seveas** [comment]
And there's no way for the API to sign in with 2fa and generate a token. Yay :(

I'm sorry, I have to close this ticket without fixing the issues you reported. If you can think of a way to fix them, I'll happily reopen it.
