### ISSUE TITLE
Conflicting credential helpers.

### ISSUE THREAD

**Issue by dschaper** [seveas/git-spindle#168]
`git-spindle` 3.3.1
Installed via `python setup` (Arch linux AUR package)

When I execute any command I'm prompted for my username and password, followed by my 2FA token. I go through the process and git-spindle reports that the credentials are saved. The command I called is executed, and checking `~/.gitspindle` shows it is populated. All other calls prompt me again for the password. A second time through gives me the status that there is an OAuth credential already for me, and my settings panel on GitHub does show a token was generated.

Each time I call a command though, my other credential helper kicks in. I can tell as I'm prompted for my GPG passphrase that locks the credential helper. 

`.gitconfig` is `credential.helper=netrc -f ~/.netrc.gpg -v` as I use a gpg encrypted login via netrc for access to `https://github.com`. I've read through the other issues that note that you also use credential helper for storage of the token. 

Am I able to use `git spindle` or does my use of another credenital helper for `netrc` preclude me. The credential is `https://github.com/git/git/blob/master/contrib/credential/netrc/git-credential-netrc`.

**Comment by seveas** [comment]
Yes, you're unable to use git-spindle this way. But I consider that a bug in git-spindle :smile:

**Comment by seveas** [comment]
Fixed in e174b4a
