### ISSUE TITLE
GitLab API too old and not working anymore

### ISSUE THREAD

**Issue by fcrespo82** [seveas/git-spindle#173]
The code used for GitLab API is very old. The original author of the API already came a long way from that 0.8 version and the code ii is already on 1.3.0. See https://github.com/python-gitlab/python-gitlab

Opening this issue to track this and see if I can help migrate!

**Comment by seveas** [comment]
Any help migrating would be awesome. I do recall having patched the bundled version slightly, so be careful :smile:

**Comment by fcrespo82** [comment]
For reference.

The gitlab api is based on commit python-gitlab/python-gitlab@8e13487dfe7a480da8d40892699d0914bbb53f3d and not from the tagged 0.8 version. The file was added on 11/22/14 which got the commits from 1/11/14.

**Comment by fcrespo82** [comment]
@seveas Since version 8.8 GitLab accepts authentication by Personal Access Tokens and in [GitLab 11 it will remove v3 endpoints](https://about.gitlab.com/2017/09/22/gitlab-10-0-released/#api-v3)
Do you think that giving the user link to generate the token and then asking is enough or we should be backward compatible with older systems?

**Comment by fcrespo82** [comment]
Already got it working just changing to the private token. If you want to peek at it https://github.com/fcrespo82/git-spindle/tree/update-gitlab-python
Soon I'll try to update the module. Can you give me some pointers on how to use your test suit?

**Comment by alerque** [comment]
Any progress on this @fcrespo82? Some of us are dead in the water now that API v3 is fully removed from up to date Gitlab instances.

**Comment by fcrespo82** [comment]
Sorry @alerque I did not had the chance to update it. My work became hectic last couple of months and then I took a vacation in the last 20 days... Maybe now I can do some testing. If you can, please join us on this update.

**Comment by seveas** [comment]
I have some code ready for this, but it's not quite finished. Maybe in a
few weeks onge my kitchen is all done.

Op di 17 jul. 2018 21:15 schreef Fernando <notifications@github.com>:

**Comment by fcrespo82** [comment]
Oh, that is great!
