### ISSUE TITLE
Test suite is completely unusable

### ISSUE THREAD

**Issue by Vampire** [seveas/git-spindle#186]
Back then when I made a couple of pull requests, I also fixed a great bunch in the tests to be able to run them.
Most of these things were just hard-coded environmental things local to your development environment like hard-coded `gitlab.kaarsemaker.net`, unnecessary and undeclared dependency on `fortune`, or depending on local git configuration, and so on.

Some where even problems in the tests like wrong prerequisites (specifying lab where hub was used), order dependent verifications where order returned from API changed or was unsteady, and so on.

I didn't submit these as pull request back then yet, as I was not finished and then was hit hard by GitHub flagging and blocking the 2nd and 3rd test account.

Currently the test suite is not usable at all.
You removed Python 2 support and thus the redefinition of `raw_input` as alias for `input` for Python 3.
But the tests still define `getpass` as alias for `raw_input` which immediately fails when you try to run tests, so I guess you either didn't push all changes, or you didn't run your tests for quite some time.

Even if I fix the `getpass` part, I cannot really get the testsuite going anymore,
neither on Windows, nor on Ubuntu running in WSL2.
It fails very early in the authentication tests, not really taking the configured username and password but asking and even then not waiting for input while asking should not be necessary for the non-interactive tests.

Besides that, when I heavily worked on the tests for my pull requests I didn't send yet back then, GitHub flagged and blocked my 2. and 3. test account that your test suite requires and the support also refused to unflag them, as they are a violation of their Terms of Service. They allow any human just one normal account and one second account for automating stuff and refused to unflag the 2. and 3. account.
So this also makes your test suite pretty unusable.

Could you please at least make the tests work for your local environment again so that they at least work per-se, then I can maybe try to rebase my fixes on top of the current version.

**Comment by seveas** [comment]
I'd say it's even worse: the testsuite is hopelessly useless. The github part may be salvageable, but the gitlab and bitbucket api's have changed a _lot_, and git-spindle had to change with them in incompatible ways. When I fixed up the code itself recently, I just ignored the testsuite. Maybe the github part of it is salvageable, but I don't really have any time to work on it.
