### ISSUE TITLE
Support local git lab instances.

### ISSUE THREAD

**Issue by moonlite** [seveas/git-spindle#50]
It would be great to be able to use git-spindle with local gitlab instances (gitlab.com seems to be [hardcoded](https://github.com/seveas/git-spindle/blob/master/lib/gitspindle/gitlab.py#L33)).

The CLI could be changed to the following:

``` $ git lab merge-request <server> [<branch1:branch2>]```

where `<server>` would be a gitlab endpoint defined in `~/.gitspindle`.

**Comment by seveas** [comment]
Something like this is most definitely part of the plan (same for GitHub enterprise support). The whole reason for creating git-lab as part of git-spindle is to use it with our local gitlab instance. I'm not quite sure yet about the UI, I also want to solve the problem of git-{hub,lab} being bitchy when you have a repo in more than one location.

**Comment by moonlite** [comment]
Cool! I'll watch this for updates. :)

Thanks for the great software! It makes working with github so much smoother.

**Comment by seveas** [comment]
Note to self: thish should depend on the credential-helper integration, as otherwise ~/.gitspindle can contain far too many secrets.

**Comment by seveas** [comment]
Implemented in c419c29 but not yet documented.

**Comment by moonlite** [comment]
Wohoo! \o/

**Comment by seveas** [comment]
This did uncover a significant stupidity in how remotes are actually handled, which will delay the release a bit while I fix that.

**Comment by seveas** [comment]
2.4 now released with this feature.

**Comment by moonlite** [comment]
Cool! Great work! :)
