### ISSUE TITLE
shell completion

### ISSUE THREAD

**Issue by mattiasb** [seveas/git-spindle#51]
Git has really nice shell completion for bash (and zsh?). It would be nice to have that for git-spindle as well. 

I'm rather busy these days but I *might* get time to work on this at some point in the future.

**Comment by seveas** [comment]
I've so far shied away from creating bash/zsh completions for anything, as that :hankey: is scary :smile:. Patches are of course welcome, but it's not very likely I'll write it myself.

**Comment by moonlite** [comment]
Hehe, that's ok. :)

**Comment by moonlite** [comment]
Just wanted to let you know that I started working on this. I haven't put anything inside a repo or anything yet but [here's a gist](https://gist.github.com/moonlite/ccf611e78afb781e5f4f) of a current snapshot (right in the middle of development) if you want to give it a quick try.

Try `$ git hub ignore C<TAB>` for example.

**Comment by blueyed** [comment]
Yes, completion for Zsh would be nice.
I might look into this myself eventually, but would be also happy to just help out / improve an existing one of course.. :)

btw: it would be nice, if git-spindle could help with this, e.g. when called with `GIT_SPINDLE_COMPLETE=1` (like Django and pip provide it).  In this context: Click provides something in this regard, but apparently only for Bash currently: http://click.pocoo.org/4/bashcomplete/

(I've just discovered this tool - very nice! I was using https://github.com/github/hub previously.)

**Comment by seveas** [comment]
bash completion now added in 16f1dd1, modeled on git's own completion and using its utility functions. As I don't use zsh myself, I won't be in the position to write zsh completion. Contributions welcome, but please open a different issue for that.

**Comment by mattiasb** [comment]
Cool! I got stuck for various personal reasons. I think I got further ahead but also that your code looks better. Excited to test it out!
