### ISSUE TITLE
git-bb/git-lab: services

### ISSUE THREAD

**Issue by seveas** [seveas/git-spindle#52]
Don't feel like playing with this right now, logging issue to make sure I don't forget.

**Comment by moonlite** [comment]
Is this for bitbucket support?

**Comment by seveas** [comment]
It is. I have some unpushed code for bitbucket support, but the initial push won't include support for doing things with services. This bug is merely my external memory, so I don't forget that.

**Comment by moonlite** [comment]
Ah!

@tobias-johansson this might be interesting to you.
