### ISSUE TITLE
Latest released version requires six; does not automatically install it

### ISSUE THREAD

**Issue by martey** [seveas/git-spindle#71]
While the master branch [no longer requires six](c39a9cacecad4f8009c5860e7771cf22b180949e), it is still necessary when installing git-spindle 2.3 from PyPi. Since six is not listed in setup.py's `install_requires`, it is not installed automatically.

This could be fixed by either backporting the change to remove six or updating setup.py to require it, and then releasing a new version to PyPi.

**Comment by seveas** [comment]
Backport to what? There's only one branch :) I need to find time to do a realease to get all these bugfixes out there.

**Comment by seveas** [comment]
2.4 has now been released.
