### ISSUE TITLE
GHE Create Repo Error

### ISSUE THREAD

**Issue by brandonzimmerman** [seveas/git-spindle#74]
When trying to create a repo using Github Enterprise the following error is thrown:

~/testrepo (master)
$ git hub create -d "test"
Traceback (most recent call last):
  File "c:\Python27\Scripts\git-hub", line 5, in <module>
    GitHub().main()
  File "c:\Python27\lib\site-packages\gitspindle\__init__.py", line 214, in main
    host = self.repository(opts, True)
  File "c:\Python27\lib\site-packages\gitspindle\__init__.py", line 158, in repository
    return host
UnboundLocalError: local variable 'host' referenced before assignment

**Comment by seveas** [comment]
Looks like you made your default account the GHE account. That's something missing in my tests and I see new where it goes wrong. Patch (and new release) incoming.

**Comment by seveas** [comment]
e5b207b should fix it (the same bug applies to the support for local gitlab instances, and this is now fixed). Are you comfortable testing an unreleased version? If so, please test and comment.

**Comment by seveas** [comment]
No response in 5 months, closing the issue assuming that I indeed fixed it.
