### ISSUE TITLE
Fork fails for projects you are a member of

### ISSUE THREAD

**Issue by jrbyrne** [seveas/git-spindle#76]
If there is a project belonging to another user (e.g. `otheruser/project_a`) which I am a member of and I try and fork it with `git lab fork`, it fails like this:

    $ git lab fork otheruser/projecta
    Repository already exists

The problem is that it is finding that I have a project with the same name, but this shouldn't prevent me doing a fork as it belongs to a different user. I have worked around this by modifying the fork function in gitlab.py like this:

    -        if repo.name in [x.name for x in self.gl.Project()]:
    -            err("Repository already exists")
    +        my_repo = self.find_repo(self.my_login, repo.name)
    +        if my_repo:
    +            err("Repository already exists")

This seems to solve the problem, but is there a better solution?

**Comment by seveas** [comment]
That solution seems fine, so I applied your pull request. Thanks!
