### ISSUE TITLE
cat/ls should work with relative paths

### ISSUE THREAD

**Issue by mattiasb** [seveas/git-spindle#82]
While working on bash completion I found myself going through a lot of hassle to be able to complete `git hub ls` and `git hub cat` while standing in a subdir of a git repo. This is because `cat` and `ls` can't handle relative paths.

To show what I mean:
```shell
$ git hub clone seveas/git-spindle
$ cd git-spindle
$ git hub ls lib/gitspindle/ # This works as expected
$ cd lib
$ git hub ls gitspindle/     # This fails with "No such directory: gitspindle/"
```

I think it would make sense if `cat` and `ls` would take the current `$PWD` into account, what do you think?

**Comment by seveas** [comment]
I think it would make sense, as long as `../` and `./` are handled sensibly as well. And maybe `/` as a prefix should mean 'root of the repo'. So in your example, `../lib`, `/lib` and `./../lib/./gitspindle` should all DTRT.

**Comment by moonlite** [comment]
Makes sense! I'll try to cook up a patch when I get the time.
