### ISSUE TITLE
"AttributeError: 'Repository' object has no attribute 'remote'" when pushing a branch

### ISSUE THREAD

**Issue by eagleoneraptor** [seveas/git-spindle#84]
My team and I are working in a single repository per project (I mean, without personal forks), we create branches and PR those branches to master to do code reviews.

So, what I do is create a branch for my changes, commit some code and execute `git hub pull-request` without arguments since the defaults works fine for me.

git-spindle ask me to push the branch before creating the pull-request, good!

```
Branch my-branch does not exist in your GitHub repo, shall I push? [Y/n] y
```

When I answer "yes", I've got the following:

```
Traceback (most recent call last):
  File "/usr/local/bin/git-hub", line 11, in <module>
    GitHub().main()
  File "/usr/local/lib/python2.7/dist-packages/gitspindle/__init__.py", line 252, in main
    func(opts)
  File "/usr/local/lib/python2.7/dist-packages/gitspindle/github.py", line 791, in pull_request
    self.gitm('push', repo.remote, src, redirect=False)
AttributeError: 'Repository' object has no attribute 'remote'
```

Looking at `github3.repos.repo.Repository` class, I indeed don't see the `remote` attribute there nor in the parent classes.

**Comment by seveas** [comment]
This is fixed in 17f376f
