### ISSUE TITLE
downstream git-spindle to debian distro package repo

### ISSUE THREAD

**Issue by smemsh** [seveas/git-spindle#92]
There's Debian control files in the source, on a Debian branch,
but `git-spindle` doesn't appear to be in the Debian package
repository under that name or any I could find.

Furthermore, Debian's `git-hub` packages appear to be something
else unrelated, by a different author.

Are there plans to send this downstream to Debian as `git-spindle`
or is the `debian` branch only for people that want to do their
own local package installs?

**Comment by seveas** [comment]
I have no plans to submit git-spindle for inclusion in any distro, but have no objection to other people trying to do so. The debian control files are on a different branch for that reason: Debian doesn't like it if upstreams ship control files. I do ship packages on launchpad though: https://launchpad.net/~dennis/+archive/ubuntu/devtools/+packages
