### ISSUE TITLE
AttributeError: 'Project' object has no attribute 'owner'

### ISSUE THREAD

**Issue by raine** [seveas/git-spindle#96]
I did `git lab add-account --host=private-gitlab-instance foo` and tried creating a new merge request and got this:

```
$ git lab merge-request
Traceback (most recent call last):
  File "/usr/local/bin/git-lab", line 11, in <module>
    GitLab().main()
  File "/usr/local/lib/python2.7/site-packages/gitspindle/__init__.py", line 309, in main
    func(opts)
  File "/usr/local/lib/python2.7/site-packages/gitspindle/gitlab.py", line 645, in merge_request
    #""" % (repo.namespace.name, src, parent.owner.username, dst)
AttributeError: 'Project' object has no attribute 'owner'
```

**Comment by seveas** [comment]
That's not very good. Which version of GitLab and git-spindle are you using?

**Comment by raine** [comment]
Latest from pip and 

GitLab 8.2.1-ee
GitLab Shell 2.6.8
GitLab API v3

**Comment by seveas** [comment]
That's the same as gitlab.com, so it should work. I'll have a look later tonight or tomorrow.

**Comment by raine** [comment]
Any luck with this?

**Comment by seveas** [comment]
Not yet, sorry.

**Comment by seveas** [comment]
cb58956 should fix this. Please test.

**Comment by seveas** [comment]
Tested it myself and it works.
